import { type NextPage } from "next";
import React from "react";
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Card from "~/components/card";
import { LoadingPage } from "~/components/loading";
// import Link from "next/link";

import { api } from "~/utils/api";
import { Separator } from "~/components/ui/separator";
// import { type RouterOutputs } from "../utils/api";

const Pinned: NextPage = () => {
  const { user } = useUser();

  if (!user) return <div>Please Sign In</div>;

  const { data, isLoading, isError } = api.notes.getUserPinned.useQuery(
    {
      userId: user.id,
    },
    { refetchOnWindowFocus: false }
  );

  if (isLoading) return <LoadingPage />;
  if (!data || isError) return <div>Something Went Wrong</div>;

  return (
    <>
      <Head>
        <title>Pinned Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 p-2 md:p-6">
        <div className="pb-2 pt-2">Search</div>
        <Separator />
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {data.map((note) => (
            <Card key={note.id} data={note} />
          ))}
          {data.length === 0 && <div>No Notes Found</div>}
        </div>
      </main>
    </>
  );
};

export default Pinned;
